module.exports = {
  apps: [
    {
      name: "listing-agent",
      script: "./agents/listing-agent.js",
      autorestart: true,
      out_file: "logs/listing.log",
      error_file: "logs/listing-err.log",
    },
    {
      name: "buyer-agent",
      script: "./agents/buyer-agent.js",
      autorestart: true,
      out_file: "logs/buyer.log",
      error_file: "logs/buyer-err.log",
    },
    {
      name: "deal-desk-agent",
      script: "./agents/deal-desk-agent.js",
      autorestart: true,
      out_file: "logs/deal-desk.log",
      error_file: "logs/deal-desk-err.log",
    },
    {
      name: "gsb-realtor-agent",
      script: "./agents/gsb-realtor-agent.js",
      autorestart: true,
      out_file: "logs/gsb-realtor.log",
      error_file: "logs/gsb-realtor-err.log",
    },
    {
      name: "nnn-scout-agent",
      script: "./agents/nnn-scout-agent.js",
      autorestart: true,
      out_file: "logs/nnn.log",
      error_file: "logs/nnn-err.log",
    },
    {
      name: "rnd-scanner",
      script: "./agents/rnd-scanner.js",
      autorestart: true,
      out_file: "logs/rnd.log",
      error_file: "logs/rnd-err.log",
    },
    {
      name: "email-agent",
      script: "./agents/email-agent.js",
      autorestart: true,
      out_file: "logs/email.log",
      error_file: "logs/email-err.log",
    },
    {
      name: "garbage-collect",
      script: "./ops/garbage-collect.js",
      autorestart: true,
      out_file: "logs/gc.log",
      error_file: "logs/gc-err.log",
    },
    {
      name: "weekly-digest",
      script: "./agents/weekly-digest.js",
      autorestart: true,
      out_file: "logs/weekly.log",
      error_file: "logs/weekly-err.log",
    },
  ],
}
